# Generated by Django 4.2.7 on 2025-06-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completado'),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado del Onboarding'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Plan Gratuito'), ('basic', 'Plan Básico'), ('professional', 'Plan Profesional'), ('enterprise', 'Plan Empresarial')], default='free', max_length=50, verbose_name='Plan de Suscripción (Deprecado)'),
        ),
    ]
