# Generated by Django 4.2.7 on 2025-07-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_cover_image_organization_gallery_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('internal', 'Cliente Interno'), ('registered', 'Cliente Registrado'), ('guest', 'Cliente Invitado')], default='internal', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='client',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='client',
            name='guest_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='guest_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Acepta Marketing'),
        ),
        migrations.AddField(
            model_name='client',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
