# Generated by Django 5.1 on 2025-07-06 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organization_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='America/Santiago', help_text='Zona horaria del profesional', max_length=50)),
                ('min_booking_notice', models.PositiveIntegerField(default=60, help_text='Tiempo mínimo de anticipación para reservas (minutos)')),
                ('max_booking_advance', models.PositiveIntegerField(default=10080, help_text='Tiempo máximo de anticipación para reservas (minutos)')),
                ('slot_duration', models.PositiveIntegerField(default=30, help_text='Duración de cada slot de tiempo (minutos)')),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_bookings', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='organizations.professional')),
            ],
            options={
                'verbose_name': 'Horario de Profesional',
                'verbose_name_plural': 'Horarios de Profesionales',
                'db_table': 'schedule_professional_schedule',
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='schedule.professionalschedule')),
            ],
            options={
                'verbose_name': 'Horario Semanal',
                'verbose_name_plural': 'Horarios Semanales',
                'db_table': 'schedule_weekly_schedule',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('professional_schedule', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(default='Descanso', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='schedule.weeklyschedule')),
            ],
            options={
                'verbose_name': 'Descanso',
                'verbose_name_plural': 'Descansos',
                'db_table': 'schedule_break',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='schedule.professionalschedule')),
            ],
            options={
                'verbose_name': 'Slot de Disponibilidad',
                'verbose_name_plural': 'Slots de Disponibilidad',
                'db_table': 'schedule_availability_slot',
                'ordering': ['date', 'start_time'],
                'unique_together': {('professional_schedule', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('unavailable', 'No Disponible'), ('vacation', 'Vacaciones'), ('sick_leave', 'Licencia Médica'), ('special_hours', 'Horario Especial'), ('holiday', 'Día Festivo')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='schedule.professionalschedule')),
            ],
            options={
                'verbose_name': 'Excepción de Horario',
                'verbose_name_plural': 'Excepciones de Horarios',
                'db_table': 'schedule_exception',
                'ordering': ['date'],
                'unique_together': {('professional_schedule', 'date')},
            },
        ),
    ]
