# Generated by Django 4.2.7 on 2025-07-20 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_clientnote_clientfile'),
        ('plans', '0003_organizationsubscription_current_receptionists_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=500, verbose_name='Access Token')),
                ('public_key', models.CharField(max_length=500, verbose_name='Public Key')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=500, verbose_name='Client Secret')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Modo Sandbox')),
                ('webhook_url', models.URLField(verbose_name='URL del Webhook')),
                ('auto_recurring', models.BooleanField(default=True, verbose_name='Pagos Recurrentes Automáticos')),
                ('retry_attempts', models.PositiveIntegerField(default=3, verbose_name='Intentos de Reintento')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración MercadoPago',
                'verbose_name_plural': 'Configuraciones MercadoPago',
                'db_table': 'payments_mercadopago_config',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mp_resource', models.CharField(max_length=100, verbose_name='Recurso MP')),
                ('mp_topic', models.CharField(max_length=100, verbose_name='Tópico MP')),
                ('mp_resource_id', models.CharField(max_length=200, verbose_name='ID del Recurso')),
                ('raw_data', models.JSONField(verbose_name='Datos Crudos')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Falló'), ('ignored', 'Ignorado')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'db_table': 'payments_webhook_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mp_subscription_id', models.CharField(max_length=200, unique=True, verbose_name='ID Suscripción MP')),
                ('mp_preapproval_id', models.CharField(blank=True, max_length=200, verbose_name='ID Preaprobación MP')),
                ('mp_payer_id', models.CharField(max_length=200, verbose_name='ID Pagador MP')),
                ('frequency', models.PositiveIntegerField(default=1, verbose_name='Frecuencia')),
                ('frequency_type', models.CharField(choices=[('months', 'Meses'), ('days', 'Días'), ('years', 'Años')], default='months', max_length=10, verbose_name='Tipo de Frecuencia')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Transacción')),
                ('mp_status', models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado en MP')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('next_payment_date', models.DateTimeField(verbose_name='Próximo Pago')),
                ('retry_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos de Reintento')),
                ('max_retry_attempts', models.PositiveIntegerField(default=3, verbose_name='Máximo Intentos')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_subscription', to='plans.organizationsubscription')),
            ],
            options={
                'verbose_name': 'Suscripción de Pago',
                'verbose_name_plural': 'Suscripciones de Pago',
                'db_table': 'payments_subscription_payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mp_payment_method_id', models.CharField(max_length=200, verbose_name='ID Método de Pago MP')),
                ('mp_customer_id', models.CharField(max_length=200, verbose_name='ID Cliente MP')),
                ('mp_card_id', models.CharField(blank=True, max_length=200, verbose_name='ID Tarjeta MP')),
                ('card_last_four_digits', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_first_six_digits', models.CharField(max_length=6, verbose_name='Primeros 6 dígitos')),
                ('card_brand', models.CharField(max_length=50, verbose_name='Marca de la tarjeta')),
                ('card_holder_name', models.CharField(max_length=200, verbose_name='Nombre del titular')),
                ('expiration_month', models.PositiveIntegerField(verbose_name='Mes de expiración')),
                ('expiration_year', models.PositiveIntegerField(verbose_name='Año de expiración')),
                ('is_default', models.BooleanField(default=False, verbose_name='Método por defecto')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'payments_payment_method',
                'unique_together': {('organization', 'mp_card_id')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mp_payment_id', models.CharField(max_length=200, unique=True, verbose_name='ID Pago MP')),
                ('mp_preference_id', models.CharField(blank=True, max_length=200, verbose_name='ID Preferencia MP')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency_id', models.CharField(default='CLP', max_length=3, verbose_name='Moneda')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('external_reference', models.CharField(blank=True, max_length=200, verbose_name='Referencia Externa')),
                ('mp_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('authorized', 'Autorizado'), ('in_process', 'En Proceso'), ('in_mediation', 'En Mediación'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo')], default='pending', max_length=20, verbose_name='Estado en MP')),
                ('mp_status_detail', models.CharField(blank=True, max_length=100, verbose_name='Detalle del Estado')),
                ('mp_operation_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Operación')),
                ('mp_payment_type_id', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Pago')),
                ('mp_payment_method_id', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('mp_date_created', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Creación MP')),
                ('mp_date_approved', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación MP')),
                ('mp_date_last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización MP')),
                ('mp_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comisión MP')),
                ('net_received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Neto Recibido')),
                ('mp_raw_data', models.JSONField(blank=True, default=dict, verbose_name='Datos Completos de MP')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod')),
                ('subscription_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.subscriptionpayment')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
