# Generated by Django 4.2.7 on 2025-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_local',
            field=models.DateTimeField(blank=True, help_text='Último login en hora local de Chile', null=True),
        ),
    ]
