# Generated by Django 4.2.7 on 2025-07-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_last_login_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False, help_text='Requiere cambio de contraseña en el siguiente login'),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Contraseña temporal generada automáticamente', max_length=255, null=True),
        ),
    ]
