# Generated by Django 4.2.7 on 2025-06-26 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_organization_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Anual')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Original (para mostrar descuentos)')),
                ('max_professionals', models.IntegerField(help_text='Número máximo de profesionales permitidos', verbose_name='Máximo de Profesionales')),
                ('max_services', models.IntegerField(help_text='Número máximo de servicios permitidos', verbose_name='Máximo de Servicios')),
                ('max_monthly_appointments', models.IntegerField(help_text='Número máximo de citas por mes', verbose_name='Máximo de Citas Mensuales')),
                ('max_clients', models.IntegerField(default=1000, help_text='Número máximo de clientes en la base de datos', verbose_name='Máximo de Clientes')),
                ('features', models.JSONField(default=list, help_text='Lista de características incluidas en el plan', verbose_name='Características')),
                ('supports_integrations', models.BooleanField(default=False)),
                ('supports_advanced_reports', models.BooleanField(default=False)),
                ('supports_multi_location', models.BooleanField(default=False)),
                ('supports_custom_branding', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('color_scheme', models.CharField(choices=[('emerald', 'Emerald'), ('blue', 'Blue'), ('purple', 'Purple'), ('gradient', 'Gradient')], default='emerald', max_length=20)),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Texto del Badge')),
                ('discount_text', models.CharField(blank=True, max_length=20, verbose_name='Texto del Descuento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'plans_plan',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('temp_token', models.CharField(max_length=255, unique=True, verbose_name='Token Temporal')),
                ('registration_data', models.JSONField(default=dict, help_text='Datos temporales del proceso de registro', verbose_name='Datos de Registro')),
                ('onboarding_step', models.PositiveIntegerField(default=0, verbose_name='Paso del Onboarding')),
                ('completed_steps', models.JSONField(default=list, verbose_name='Pasos Completados')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Registro Completado')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Registro Expirado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creado')),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='Plan Seleccionado')),
            ],
            options={
                'verbose_name': 'Registro de Usuario',
                'verbose_name_plural': 'Registros de Usuarios',
                'db_table': 'plans_user_registration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Periodo de Prueba'), ('active', 'Activa'), ('past_due', 'Pago Pendiente'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('current_professionals_count', models.PositiveIntegerField(default=0)),
                ('current_services_count', models.PositiveIntegerField(default=0)),
                ('current_clients_count', models.PositiveIntegerField(default=0)),
                ('current_month_appointments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Suscripción de Organización',
                'verbose_name_plural': 'Suscripciones de Organizaciones',
                'db_table': 'plans_organization_subscription',
            },
        ),
    ]
