# Generated by Django 4.2.7 on 2025-06-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='current_users_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(default=1, help_text='Número máximo de usuarios del sistema permitidos', verbose_name='Máximo de Usuarios'),
            preserve_default=False,
        ),
    ]
