# Generated by Django 5.1 on 2025-06-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_organizationsubscription_current_users_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='current_receptionists_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='current_staff_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_receptionists',
            field=models.IntegerField(default=1, help_text='Número máximo de recepcionistas permitidos', verbose_name='Máximo de Recepcionistas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_staff',
            field=models.IntegerField(default=1, help_text='Número máximo de staff permitidos', verbose_name='Máximo de Staff'),
        ),
    ]
